#**Python** **For** **AI** **Libraries** **setup** **and** **istallation**

In [ ]:
pip install pandas

In [ ]:
%%time
import pandas as pd


CPU times: user 8 µs, sys: 0 ns, total: 8 µs
Wall time: 11.4 µs


In [ ]:
pip install numpy


In [ ]:
import numpy as np

In [ ]:
my_list=[1,2,3]
print(my_list)

[1, 2, 3]


In [ ]:
type(my_list)
type(np.array(my_list))

numpy.ndarray

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.rand(3,6)

array([[0.04484028, 0.74908287, 0.52568061, 0.69509293, 0.53085572,
        0.02594568],
       [0.78345598, 0.43376896, 0.4755869 , 0.94389839, 0.93035641,
        0.49306959],
       [0.91964068, 0.34237774, 0.99118761, 0.82118428, 0.59909239,
        0.32905518]])

In [ ]:
arr=np.arange(25)

In [ ]:
ranarr = np.random.randint(0,50,10)

In [ ]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([19, 14, 26,  9, 23,  5, 43, 28, 29, 17])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.max()

np.int64(24)

In [ ]:
arr.min()

np.int64(0)

numpy indxing and selection


In [ ]:
arr=np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr[10]

np.int64(10)

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

broadcasting

In [ ]:
arr[0:5]=100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Pandas library in python

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/student_performance_100_rows-1.csv")

In [ ]:
df

,Student_ID,Age,Study_Hours,Attendance,Previous_Score,Assignments_Score,Final_Score,Result
0,1,18,2.5,75,62,65,66,Pass
1,2,19,3.0,82,70,72,73,Pass
2,3,18,1.5,68,55,58,59,Fail
3,4,20,4.0,95,85,88,88,Pass
4,5,19,3.5,88,78,80,81,Pass
...,...,...,...,...,...,...,...,...
95,96,18,2.0,70,55,58,59,Fail
96,97,20,4.5,92,88,91,90,Pass
97,98,19,3.0,83,72,75,75,Pass
98,99,21,5.0,96,94,96,95,Pass


In [ ]:
print(df.to_string())

    Student_ID  Age  Study_Hours  Attendance  Previous_Score  Assignments_Score  Final_Score Result
0            1   18          2.5          75              62                 65           66   Pass
1            2   19          3.0          82              70                 72           73   Pass
2            3   18          1.5          68              55                 58           59   Fail
3            4   20          4.0          95              85                 88           88   Pass
4            5   19          3.5          88              78                 80           81   Pass
5            6   18          2.0          72              60                 63           63   Pass
6            7   21          5.0          98              91                 94           93   Pass
7            8   20          4.5          91              88                 90           89   Pass
8            9   19          3.0          84              73                 75           76   Pass


In [ ]:
df.loc[3]

,3
Student_ID,4
Age,20
Study_Hours,4.0
Attendance,95
Previous_Score,85
Assignments_Score,88
Final_Score,88
Result,Pass


In [ ]:
df.loc[[0,1]]

,Student_ID,Age,Study_Hours,Attendance,Previous_Score,Assignments_Score,Final_Score,Result
0,1,18,2.5,75,62,65,66,Pass
1,2,19,3.0,82,70,72,73,Pass


In [ ]:
df.shape

(100, 8)

In [ ]:
df.head()

,Student_ID,Age,Study_Hours,Attendance,Previous_Score,Assignments_Score,Final_Score,Result
0,1,18,2.5,75,62,65,66,Pass
1,2,19,3.0,82,70,72,73,Pass
2,3,18,1.5,68,55,58,59,Fail
3,4,20,4.0,95,85,88,88,Pass
4,5,19,3.5,88,78,80,81,Pass


In [ ]:
del df["Student_ID"]

In [ ]:
df


,Age,Study_Hours,Attendance,Previous_Score,Assignments_Score,Final_Score,Result
0,18,2.5,75,62,65,66,Pass
1,19,3.0,82,70,72,73,Pass
2,18,1.5,68,55,58,59,Fail
3,20,4.0,95,85,88,88,Pass
4,19,3.5,88,78,80,81,Pass
...,...,...,...,...,...,...,...
95,18,2.0,70,55,58,59,Fail
96,20,4.5,92,88,91,90,Pass
97,19,3.0,83,72,75,75,Pass
98,21,5.0,96,94,96,95,Pass


In [ ]:
df


,Student_ID,Age,Study_Hours,Attendance,Previous_Score,Assignments_Score,Final_Score,Result
0,1,18,2.5,75,62,65,66,Pass
1,2,19,3.0,82,70,72,73,Pass
2,3,18,1.5,68,55,58,59,Fail
3,4,20,4.0,95,85,88,88,Pass
4,5,19,3.5,88,78,80,81,Pass
...,...,...,...,...,...,...,...,...
95,96,18,2.0,70,55,58,59,Fail
96,97,20,4.5,92,88,91,90,Pass
97,98,19,3.0,83,72,75,75,Pass
98,99,21,5.0,96,94,96,95,Pass


In [ ]:
df.filter(["Student_ID","Age"])

,Student_ID,Age
0,1,18
1,2,19
2,3,18
3,4,20
4,5,19
...,...,...
95,96,18
96,97,20
97,98,19
98,99,21


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Student_ID         100 non-null    int64  
 1   Age                100 non-null    int64  
 2   Study_Hours        100 non-null    float64
 3   Attendance         100 non-null    int64  
 4   Previous_Score     100 non-null    int64  
 5   Assignments_Score  100 non-null    int64  
 6   Final_Score        100 non-null    int64  
 7   Result             100 non-null    object 
dtypes: float64(1), int64(6), object(1)
memory usage: 6.4+ KB


In [ ]:
df=df.dropna()
df

,Student_ID,Age,Study_Hours,Attendance,Previous_Score,Assignments_Score,Final_Score,Result
0,1,18,2.5,75,62,65,66,Pass
1,2,19,3.0,82,70,72,73,Pass
2,3,18,1.5,68,55,58,59,Fail
3,4,20,4.0,95,85,88,88,Pass
4,5,19,3.5,88,78,80,81,Pass
...,...,...,...,...,...,...,...,...
95,96,18,2.0,70,55,58,59,Fail
96,97,20,4.5,92,88,91,90,Pass
97,98,19,3.0,83,72,75,75,Pass
98,99,21,5.0,96,94,96,95,Pass


In [ ]:
df=df.dropna(inplace=True)


In [ ]:
df

,Student_ID,Age,Study_Hours,Attendance,Previous_Score,Assignments_Score,Final_Score,Result
0,1,18,2.5,75,62,65,66,Pass
1,2,19,3.0,82,70,72,73,Pass
2,3,18,1.5,68,55,58,59,Fail
3,4,20,4.0,95,85,88,88,Pass
4,5,19,3.5,88,78,80,81,Pass
...,...,...,...,...,...,...,...,...
95,96,18,2.0,70,55,58,59,Fail
96,97,20,4.5,92,88,91,90,Pass
97,98,19,3.0,83,72,75,75,Pass
98,99,21,5.0,96,94,96,95,Pass


In [ ]:
df["Attendance"].median()

86.0

In [ ]:
df["Study_Hours"]=pd.to_datetime(df['Study_Hours'])

In [ ]:
df

,Student_ID,Age,Study_Hours,Attendance,Previous_Score,Assignments_Score,Final_Score,Result
0,1,18,1970-01-01 00:00:00.000000002,75,62,65,66,Pass
1,2,19,1970-01-01 00:00:00.000000003,82,70,72,73,Pass
2,3,18,1970-01-01 00:00:00.000000001,68,55,58,59,Fail
3,4,20,1970-01-01 00:00:00.000000004,95,85,88,88,Pass
4,5,19,1970-01-01 00:00:00.000000003,88,78,80,81,Pass
...,...,...,...,...,...,...,...,...
95,96,18,1970-01-01 00:00:00.000000002,70,55,58,59,Fail
96,97,20,1970-01-01 00:00:00.000000004,92,88,91,90,Pass
97,98,19,1970-01-01 00:00:00.000000003,83,72,75,75,Pass
98,99,21,1970-01-01 00:00:00.000000005,96,94,96,95,Pass
